version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hackaton2
      - POSTGRES_USER=Nurik
      - POSTGRES_PASSWORD=1
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./hackaton2:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db